<?php

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <section id="add_funds-form" class="padded">
        <h3>Add Funds</h3>
        <form method="post" action="/account/addFunds">
            <div class="form-group">
                <input type="number" step="0.01" name="amount" class="form-control" id="input-amount" placeholder="Amount">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Add">
            </div>
        </form>
    </section>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
